### ISSUE TITLE
优化

### ISSUE THREAD

**Issue by hms58** [wuruofan/xmlabit#1]
属性不方便对比，希望能加下属性key排序

**Comment by wuruofan** [comment]
Hi，需求可以描述的详细点么？最好能给个前后数据的对比，也方便我改进时测试哈 😀

**Comment by hms58** [comment]
感谢回复哈！示例如下

1.原始数据：

`<?xml version="1.0" encoding="utf-8"?>
<bookstore>
  <books>
	<book name="name1" price="10" lang="us"/>
    <book lang="eng" price="29.99" name="name2"/>
    <book price="2" lang="fr" name="name3"/>
  </books>
</bookstore>`


2. 期望得到的结果（lang、name和price等属性升序，book项是按name排序）

`<?xml version="1.0" encoding="utf-8"?>
<bookstore>
  <books>
   <book lang="us" name="name1" price="10"/>
    <book lang="eng" name="name2" price="29.99"/>
    <book lang="fr" name="name3" price="2"/>
  </books>
</bookstore>`


![image](https://user-images.githubusercontent.com/7508625/129909033-68419e48-e112-4f87-9628-a333a7f50fd2.png)


3. 属性key没有排序，不方便对比差异

![image](https://user-images.githubusercontent.com/7508625/129908380-fad946a2-ac4e-4ef2-9bf2-4e7e7f1d2a7e.png)

**Comment by wuruofan** [comment]
> 感谢回复哈！示例如下
> 
> 1.原始数据：
> 
> `<?xml version="1.0" encoding="utf-8"?> <bookstore> <books> <book name="name1" price="10" lang="us"/> <book lang="eng" price="29.99" name="name2"/> <book price="2" lang="fr" name="name3"/> </books> </bookstore>`
> 
> 1. 期望得到的结果（lang、name和price等属性升序，book项是按name排序）
> 
> `<?xml version="1.0" encoding="utf-8"?> <bookstore> <books> <book lang="us" name="name1" price="10"/> <book lang="eng" name="name2" price="29.99"/> <book lang="fr" name="name3" price="2"/> </books> </bookstore>`
> 
> ![image](https://user-images.githubusercontent.com/7508625/129909033-68419e48-e112-4f87-9628-a333a7f50fd2.png)
> 
> 1. 属性key没有排序，不方便对比差异
> 
> ![image](https://user-images.githubusercontent.com/7508625/129908380-fad946a2-ac4e-4ef2-9bf2-4e7e7f1d2a7e.png)

ok，我明白了，属性名也按a-z排序，我研究下哈

**Comment by wuruofan** [comment]
Already done in version 0.2.4~
